### ISSUE TITLE
NoMethodError: undefined method `binds' for #<ActiveRecord::Relation::

### ISSUE THREAD

**Issue by ifebrand6** [Liooo/dynabute#2]
Request.dynabutes << Dynabute::Field.new( name: 'gender', value_type: 'select', options_attributes: [ { label: 'male' }, { label: 'female' } ] )
when i push the  Dynabute:field... to Request.dynabutes obj, it returns a Nomethod error.

**Comment by CrAsH1101** [comment]
I don't know if that syntax worked with previous versions of Rails, but I believe proper Rails way would be a better option.
Please see ma PR https://github.com/Liooo/dynabute/pull/3
